/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AiodHeader {
        /**
          * @default '/'
         */
        "homeUrl": string;
        /**
          * @default false
         */
        "isLoggedIn": boolean;
        /**
          * @default '#'
         */
        "loginUrl": string;
        /**
          * @default 'https://via.placeholder.com/40x40?text=U'
         */
        "userAvatarUrl": string;
        /**
          * @default ''
         */
        "userName": string;
        /**
          * @default 'default'
         */
        "variant": 'default' | 'dashboard';
    }
}
declare global {
    interface HTMLAiodHeaderElement extends Components.AiodHeader, HTMLStencilElement {
    }
    var HTMLAiodHeaderElement: {
        prototype: HTMLAiodHeaderElement;
        new (): HTMLAiodHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "aiod-header": HTMLAiodHeaderElement;
    }
}
declare namespace LocalJSX {
    interface AiodHeader {
        /**
          * @default '/'
         */
        "homeUrl"?: string;
        /**
          * @default false
         */
        "isLoggedIn"?: boolean;
        /**
          * @default '#'
         */
        "loginUrl"?: string;
        /**
          * @default 'https://via.placeholder.com/40x40?text=U'
         */
        "userAvatarUrl"?: string;
        /**
          * @default ''
         */
        "userName"?: string;
        /**
          * @default 'default'
         */
        "variant"?: 'default' | 'dashboard';
    }
    interface IntrinsicElements {
        "aiod-header": AiodHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "aiod-header": LocalJSX.AiodHeader & JSXBase.HTMLAttributes<HTMLAiodHeaderElement>;
        }
    }
}
